### ISSUE TITLE
Generalized Maxwell for viscoelastic liquids

### ISSUE THREAD

**Issue by mirandi1** [NREL/pyvisco#2]
Would it be possible to decide between the equations for a viscoelastic solid and the ones for a viscoelastic liquid? That is, to remove the parameter E_∞ from the E' equation.

**Comment by martin-springer** [comment]
@mirandi1 - Sorry for the delayed response. If that is still of interest to you, I would like to learn more about viscoelastic liquids. The current routine is implemented in such a way that E_inf/E_0 >= eps, where eps = 1E-3. This way, numerical difficulties are avoided in structural FEM simulations. Would decreasing the eps value already help to make the routine work for viscoelastic liquids?

**Comment by mirandi1** [comment]
@martin-springer Glad to read your reply, thanks! Yes, I am still interested in pyvisco. For a viscoelastic liquids (eg. a polymer solution or melt), the Generalized Maxwell model considers that the material is flowing, so the prony series take E_inf as 0 in such case. Removing the process to find E_inf would be perhaps a solution.

**Comment by martin-springer** [comment]
@mirandi1 - The new release allows E_inf = 0. Maybe that change is sufficient to apply pyvisco for viscoelastic liquids?
