### ISSUE TITLE
Error in mastercurve creation using shift algorithm

### ISSUE THREAD

**Issue by moryant** [NREL/pyvisco#4]
In the Jupyter notebook "verify_freq_raw.ipynb" if the shift algorithm is used:

` df_aT = visco.master.get_aT(df_raw, RefT)`
 Instead of the shift factors imported from .xls table, then when the mastercuve function is called :
`df_master = visco.master.get_curve(df_raw, df_aT, RefT)`
 There is a type error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_21464/2365528376.py in <module>
      1 #Create master curve
----> 2 df_master = visco.master.get_curve(df_raw, df_aT, RefT)
      3 fig_master_shift = visco.master.plot_shift(df_raw, df_master, units)

~\AppData\Roaming\Python\Python39\site-packages\pyvisco\master.py in get_curve(df_raw, df_aT, RefT)
    358     df_shift = pd.DataFrame()
    359     for S, df in df_raw.groupby('Set'):
--> 360         aT = 10**(df_aT[df_aT['T'] == df['T_round'].iloc[0]]['log_aT'].values)
    361         fshift = aT * df['f_set']
    362         df_shift = pd.concat([df_shift, fshift.to_frame()])

TypeError: tuple indices must be integers or slices, not str
```

**Comment by moryant** [comment]
It looks like the function `pyvisco.master.get_aT(df_raw, RefT)` return a tuple instead of returning a dataframe as it is written in the documentation: https://pyvisco.readthedocs.io/en/latest/_autosummary/pyvisco.master.html#pyvisco.master.get_aT

![df_aT_type](https://github.com/NREL/pyvisco/assets/144047514/de072dbb-af41-4ee8-a111-4254b73172bf)

**Comment by moryant** [comment]
I found a way to bypass the error by taking the first element in the tuple `df_aT` generated by the function `pyvisco.master.get_aT()` and convert it into a DataFrame with Pandas:

`#Or use shift algorithmn from this notebook (uncomment following line)`
`df_aT = visco.master.get_aT(df_raw, RefT)`
`df_aT = pd.DataFrame(df_aT[0])`
`df_aT.head()`

**Comment by martin-springer** [comment]
@moryant - Thank you for reporting this. I'll update the documentation to reflect the changes.
